Repository woodpecker-ci/plugin-ready-release-go, pull requests merged in 2023-11, with the labels that each got.

#45 Add debug option
  Dockerfile
  src/index.ts
  src/utils/change.test.ts
  src/utils/config.ts
Labels: enhancement

#46 Cleanup config
  src/cmd/prepare.ts
  src/index.ts
  src/utils/change.test.ts
  src/utils/config.ts
  src/utils/types.ts
Labels: enhancement, breaking

#43 Allow to release as RC
  Dockerfile
  README.md
  package.json
  src/cmd/prepare.ts
  src/cmd/release.ts
  src/forges/forge.ts
  src/forges/github.ts
  src/index.ts
  src/utils/change.test.ts
  src/utils/change.ts
  src/utils/pr.test.ts
  src/utils/pr.ts
  src/utils/types.ts
Labels: feature

#32 Add docs
  README.md
  docs.md
Labels: documentation

#54 Fix changelog after rc release
  Dockerfile
  package.json
  src/index.test.ts
  src/index.ts
  src/run.ts
  src/utils/__fixtures__/CHANGELOG_4.md
  src/utils/__snapshots__/change.test.ts.snap
  src/utils/change.test.ts
  src/utils/change.ts
Labels: bug

#58 Add username to workflow
  .woodpecker/release.yml
Labels: bug, build

#62 Use all commits since last none rc tag
  .woodpecker/test.yml
  package.json
  pnpm-lock.yaml
  src/index.ts
Labels: bug
