Repository woodpecker-ci/plugin-ready-release-go, pull requests merged in 2023-10, with the labels that each got.

#12 Add renovate config
  .woodpecker/release-helper.yml
  .woodpecker/release.yml
  renovate.json
Labels: internal

#33 renovate: use org config
  renovate.json
Labels: skip-changelog

#36 Add note to release PR about this plugin
  src/cmd/prepare.ts
  src/utils/types.ts
Labels: enhancement
