Repository woodpecker-ci/plugin-ready-release-go, pull requests merged in 2024-11, with the labels that each got.

#225 Enhance github pr search based on sha
  .gitignore
  src/forges/github.ts
  src/index.ts
  src/run.ts
  src/utils/config.ts
Labels: bug

#227 Create tag based on release branch
  src/cmd/release.ts
  src/forges/forge.ts
  src/forges/gitea.ts
  src/forges/github.ts
Labels: bug

#198 Add Justfile
  Justfile
Labels: build, skip-changelog

#245 Add tests for changelog generation
  .ecrc
  .editorconfig
  .woodpecker/test.yml
  src/utils/__snapshots__/change.test.ts.snap
  src/utils/change.test.ts
Labels: refactor
