Repository woodpecker-ci/plugin-ready-release-go, pull requests merged in 2024-12, with the labels that each got.

#253 Disable commentOnReleasedPullRequests by default
  docs.md
  src/utils/config.ts
Labels: breaking

#246 Keep text before changelog sections
  src/utils/change.test.ts
  src/utils/change.ts
Labels: feature

#260 Remove execa
  package.json
  pnpm-lock.yaml
Labels: internal, refactor

#267 Make sure gitea PR is open
  src/forges/gitea.ts
Labels: bug
