Repository woodpecker-ci/plugin-ready-release-go, pull requests merged in 2024-09, with the labels that each got.

#31 Describe custom label config
  README.md
Labels: documentation

#174 Update nix flake and pin nodejs to v20
  flake.lock
  flake.nix
Labels: dependencies, build

#175 Remove unused options from github provider
  src/forges/github.ts
Labels: refactor

#28 Add gitea / forgejo support
  .prettierrc.json
  Dockerfile
  README.md
  docs.md
  package.json
  pnpm-lock.yaml
  src/forges/gitea.ts
  src/forges/index.ts
  src/index.test.ts
  src/index.ts
  src/utils/change.test.ts
  src/utils/config.ts
Labels: feature

#190 Update plugin documentation
  README.md
  docs.md
Labels: documentation
